### ISSUE TITLE
与反作弊配合

### ISSUE THREAD

**Issue by Despaitre876** [MC-XiaoHei/ISeeYou#2]
icu于类似Vulcan等反作弊中，是否能添加反作弊检测疑似作弊行为之后，icu自动标记这个玩家的录像，并在服务端中单独创建出一个文件夹来管理这些录像

**Comment by MC-XiaoHei** [comment]
将优先考虑接入Matrix反作弊。

**Comment by MC-XiaoHei** [comment]
将优先考虑对接Themis Anti Cheat

**Comment by MC-XiaoHei** [comment]
已经完成，在v1.1.1发布。请自行测试
