### ISSUE TITLE
可能导致玩家无法捡起物品和无法搭方块的Bug

### ISSUE THREAD

**Issue by whzcc** [MC-XiaoHei/ISeeYou#21]
### Bug
1. 玩家捡起物品后，物品没有出现在背包，而是**直接消失**。  
2. 玩家无法在脚下搭方块。
### 猜测
1. 是因为录制用的**假人捡起物品**/占了方块的位置？  
2.  两个Bug都是偶尔出现，不确定和服务器性能有无关联，甚至不能完全确定是ISeeYou所致（尤其第二条Bug）。
3. Bug发生时后台未见ISeeYou报错。

**Comment by MC-XiaoHei** [comment]
是否安装了多世界插件？
请尝试使用最新版leaves，最新版为摄像机提供了更高强度的防护

**Comment by CerealAxis** [comment]
建议使用最新版Leaves 确保摄像师不是生存状态）

**Comment by CerealAxis** [comment]
已过时
