### ISSUE TITLE
录制假人吞玩家东西+有脚步声

### ISSUE THREAD

**Issue by NotKillerGod** [MC-XiaoHei/ISeeYou#22]
使用插件时假人会把玩家东西吞了+有脚步声
视频：
https://share.weiyun.com/EFbO3Kqs

**Comment by MC-XiaoHei** [comment]
leaves版本？

**Comment by NotKillerGod** [comment]
Leaves-847357b
1.20.1最后一个版本

**Comment by MC-XiaoHei** [comment]
这个问题是leaves的问题，1.20.4得到修复
leaves并不支持旧版本
