### ISSUE TITLE
即时重放功能

### ISSUE THREAD

**Issue by Error-106** [MC-XiaoHei/ISeeYou#3]

**Comment by MC-XiaoHei** [comment]
Leaves已提供录制并不保存功能
此功能理论上已可实现
但优先级不会太高

**Comment by MC-XiaoHei** [comment]
好的让我来看看这个issue
你希望使用什么方式去即时重放？
调用命令吗，比如
`/vcr <player> [time]`

**Comment by MC-XiaoHei** [comment]
我不知道怎么翻译这个东西（
可能叫vcr（？

**Comment by MC-XiaoHei** [comment]
我不知道怎么翻译这个东西（
可能叫vcr（？

**Comment by MC-XiaoHei** [comment]
用`/instantreplay`吧

**Comment by MC-XiaoHei** [comment]
请使用[dev build](https://github.com/MC-XiaoHei/ISeeYou/actions/runs/8934684591/artifacts/1469656060)进行测试
需要开启`instantReplay.enabled`选项

**Comment by MC-XiaoHei** [comment]
最新版已经实现
