### ISSUE TITLE
装入ICU后游戏内Tab补全无法使用，所有命令显示红色

### ISSUE THREAD

**Issue by xiaonuo6666** [MC-XiaoHei/ISeeYou#34]
Leaves 版本 1.21
ICU版本 1.3.1
装完ICU进游戏，发现登录命令/l 显示红色，但正确输入仍能登陆成功。
然后发现所有命令都没有补全，并且输入任何命令聊天框都是红色的错误提示，盲打输入正确仍能执行。
删掉ICU后恢复。

**Comment by CerealAxis** [comment]
请使用v1.3.2版本
